import Image from "next/image";
import { Header } from "@/components/header";
import { DashboardPreview } from "@/components/dashboard-preview";
import { ProductShowcase } from "@/components/product-showcase";
import { WaitlistForm } from "@/components/waitlist-form";

const deductions = [["Etsy fees","−$613"],["Product costs","−$1,327"],["Shipping","−$524"],["Expenses","−$482"],["Refunds","−$196"]];

export default function Home() {
  return (
    <main id="top" className="site-shell min-h-screen overflow-hidden">
      <div className="ambient ambient-one" /><div className="ambient ambient-two" />
      <Header />

      <section className="hero-wrap relative mx-auto max-w-[1480px] px-5 pb-24 pt-28 sm:px-8 lg:px-12 lg:pb-32 lg:pt-36">
        <div className="mx-auto max-w-5xl text-center reveal-up">
          <div className="eyebrow-chip mx-auto mb-7 w-fit"><span className="eyebrow-dot" />Built for serious online sellers</div>
          <h1 className="hero-title mx-auto max-w-5xl text-balance text-[3.45rem] font-semibold leading-[0.98] tracking-[-0.065em] sm:text-7xl lg:text-[6.75rem]">Know what your shop<span className="hero-gradient block">actually makes.</span></h1>
          <p className="mx-auto mt-7 max-w-2xl text-pretty text-base leading-7 text-white/58 sm:text-lg sm:leading-8">Automatically bring your Etsy sales, marketplace fees, product costs, expenses and refunds together—so you can see your real profit without spreadsheets or guesswork.</p>
          <div className="mt-9 flex flex-col items-center justify-center gap-3 sm:flex-row"><a className="primary-button" href="#early-access">Get early access <ArrowIcon /></a><a className="secondary-button" href="#product">See Seller Studio</a></div>
          <p className="mt-5 text-sm text-white/38">Built for Etsy sellers · Shopify coming next</p>
        </div>
        <div className="relative mx-auto mt-16 max-w-[1250px] lg:mt-20"><div className="hero-glow" /><DashboardPreview /></div>
      </section>

      <section className="border-y border-white/[0.065] bg-white/[0.018]"><div className="mx-auto grid max-w-6xl gap-8 px-6 py-9 text-center sm:grid-cols-3 sm:px-8">
        <Metric label="Revenue" value="$8,426" helper="+12.4% this month"/><Metric label="Real profit" value="$5,284" helper="62.7% margin"/><Metric label="Orders" value="184" helper="+18 vs. last month"/>
      </div></section>

      <section className="seller-proof mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-12 lg:py-20"><div className="seller-proof-card grid gap-8 rounded-[1.75rem] px-7 py-8 sm:px-9 lg:grid-cols-[0.72fr_1.28fr] lg:items-center"><div><p className="section-kicker">Built by sellers</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.05em] sm:text-4xl">We built the view we wanted for our own shop.</h2></div><p className="max-w-2xl text-base leading-7 text-white/48 lg:justify-self-end">Sales were easy to find, but the real business picture was scattered across Etsy, spreadsheets, product costs and expenses. Seller Studio brings that picture into one operating view.</p></div></section>

      <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-12 lg:py-24"><div className="grid items-center gap-14 lg:grid-cols-[0.92fr_1.08fr] lg:gap-20">
        <div><p className="section-kicker">The problem</p><h2 className="section-title mt-4 max-w-xl">Revenue is easy to see. Profit isn&apos;t.</h2><p className="mt-6 max-w-lg text-base leading-7 text-white/50 sm:text-lg sm:leading-8">Marketplace dashboards show sales. Your real business lives underneath them—in fees, refunds, product costs, shipping and operating expenses.</p><p className="mt-6 max-w-lg text-base leading-7 text-white/50">Seller Studio brings those numbers together so you can stop running your shop from spreadsheets, calculators and guesswork.</p></div>
        <div className="profit-card glass-card p-5 sm:p-7"><div className="flex items-center justify-between border-b border-white/[0.07] pb-5"><div><p className="text-sm text-white/42">This month</p><p className="mt-1 text-xl font-semibold tracking-[-0.03em]">What $8,426 in sales became</p></div><span className="status-pill">Live view</span></div><div className="space-y-4 py-6"><MoneyRow label="Revenue" value="$8,426" strong/>{deductions.map(([l,v])=><MoneyRow key={l} label={l} value={v}/>)}</div><div className="profit-total flex items-end justify-between rounded-2xl p-5"><div><p className="text-sm text-white/46">Real profit</p><p className="mt-1 text-3xl font-semibold tracking-[-0.045em]">$5,284</p></div><div className="text-right"><p className="text-sm text-white/42">Margin</p><p className="mt-1 font-medium text-white/88">62.7%</p></div></div></div>
      </div></section>

      <section id="product" className="scroll-section mx-auto max-w-7xl px-5 pb-24 sm:px-8 lg:px-12 lg:pb-32">
        <div className="mx-auto mb-10 max-w-3xl text-center"><p className="section-kicker">The product</p><h2 className="section-title mt-4">One studio. Every number that matters.</h2><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-white/48">Move from a high-level business view to the economics of a single product or order without leaving the same workspace.</p></div>
        <ProductShowcase />
      </section>

      <section className="mx-auto max-w-7xl px-5 pb-24 sm:px-8 lg:px-12 lg:pb-32"><div className="mobile-story live-product-story rounded-[2rem] border border-white/[0.08]">
        <div className="grid items-center gap-12 p-7 sm:p-10 lg:grid-cols-[1fr_.86fr] lg:p-14">
          <div><div className="live-proof-chip"><span className="live-proof-dot"/>REAL APP · LIVE BUILD</div><p className="section-kicker mt-7">Built for the way sellers work</p><h2 className="section-title mt-4 max-w-2xl">Your business, in your pocket.</h2><p className="mt-5 max-w-xl text-base leading-7 text-white/48 sm:text-lg">This is the actual Seller Studio mobile interface running during development—not a marketing mockup. Sellers can move from real profit to orders, products and Pilot without leaving the app.</p><div className="mt-7 grid gap-3 sm:grid-cols-3"><MiniBenefit value="Live" label="Etsy sync"/><MiniBenefit value="5" label="core areas"/><MiniBenefit value="1 view" label="business clarity"/></div><p className="live-build-note mt-5">Live development data shown in the device preview. Demo-shop figures elsewhere on this page are illustrative.</p></div>
          <LivePhoneMock />
        </div>
      </div></section>

      <section id="pilot" className="scroll-section mx-auto max-w-7xl px-5 pb-24 sm:px-8 lg:px-12 lg:pb-32"><div className="pilot-shell overflow-hidden rounded-[2rem] border border-white/[0.08]"><div className="grid lg:grid-cols-[0.78fr_1.22fr]"><div className="p-7 sm:p-9 lg:p-10"><p className="section-kicker">Pilot AI</p><h2 className="pilot-title mt-4">Your shop has data. Now you can talk to it.</h2><p className="mt-6 max-w-lg text-base leading-7 text-white/50">Ask questions in plain English and let Pilot turn your real business numbers into useful answers and next steps.</p><div className="mt-8 flex flex-wrap gap-2">{["Why did profit fall?","Best product this month?","Where did costs rise?"].map(q=><span className="question-chip" key={q}>{q}</span>)}</div></div><div className="pilot-panel flex items-center p-5 sm:p-7 lg:p-8"><div className="pilot-window"><div className="flex items-center justify-between border-b border-white/[0.06] px-5 py-4"><div className="flex items-center gap-3"><span className="pilot-orb">P</span><div><p className="text-sm font-medium text-white/88">Pilot</p><p className="text-xs text-white/32">Business intelligence</p></div></div><span className="status-pill">Live data</span></div><div className="space-y-5 p-5 sm:p-6"><div className="user-bubble">Why was my profit lower in August?</div><div className="pilot-bubble"><p>Revenue increased by 8.4%, but total costs grew faster.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Insight label="Packaging" value="+$183"/><Insight label="Refunds" value="+$96"/></div><p className="mt-4 text-white/54">Your Watercolor Wedding Crest remained your strongest-margin product at 68%.</p><div className="pilot-action mt-4">Focus next: reduce packaging cost per order and protect the 68% margin on your strongest product.</div></div></div></div></div></div></div></section>

      <section className="mx-auto max-w-7xl px-5 pb-24 sm:px-8 lg:px-12 lg:pb-32"><div className="trust-grid grid gap-5 lg:grid-cols-[0.9fr_1.1fr]"><div className="trust-card p-7 sm:p-9"><p className="section-kicker">Accuracy</p><h2 className="mt-4 text-4xl font-semibold leading-[1.02] tracking-[-0.055em] sm:text-5xl">Numbers you can actually trust.</h2><p className="mt-5 max-w-lg text-base leading-7 text-white/48">Seller Studio is being built around the financial details that change real profit—not rough estimates.</p></div><div className="grid gap-4 sm:grid-cols-2"><TrustItem title="Historical COGS" text="Changing a cost today does not rewrite last month."/><TrustItem title="Marketplace fees" text="Fees belong in profit, not in a separate mental calculation."/><TrustItem title="Refund handling" text="Refunds are reflected in the period where they actually happen."/><TrustItem title="Operating expenses" text="Subscriptions, packaging and business costs complete the picture."/></div></div></section>

      <section id="pricing" className="scroll-section mx-auto max-w-7xl px-5 pb-24 sm:px-8 lg:px-12 lg:pb-32"><div className="pricing-placeholder rounded-[2rem] border border-white/[0.08] px-7 py-10 sm:px-10 sm:py-12"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="section-kicker">Founding seller pricing</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.055em] sm:text-5xl">Join before public launch.</h2><p className="mt-4 max-w-2xl text-base leading-7 text-white/48">Early sellers help shape Seller Studio, get first access to private beta, and receive special founding-member pricing when paid plans open.</p><div className="mt-6 flex flex-wrap gap-2"><span className="benefit-chip">Private beta access</span><span className="benefit-chip">Founder pricing</span><span className="benefit-chip">Direct roadmap input</span></div></div><a className="primary-button" href="#early-access">Reserve early access <ArrowIcon /></a></div></div></section>

      <section id="resources" className="scroll-section mx-auto max-w-7xl px-5 pb-24 sm:px-8 lg:px-12 lg:pb-32"><div className="mb-8 max-w-2xl"><p className="section-kicker">Free seller tools</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.055em] sm:text-5xl">Useful before you ever sign in.</h2></div><div className="grid gap-4 md:grid-cols-3"><a href="/etsy-profit-calculator" className="resource-card group p-6"><div className="flex items-center justify-between"><span className="resource-number">01</span><span className="live-tool-pill">Live now</span></div><div className="resource-icon mt-9">$</div><h3 className="mt-5 text-xl font-semibold tracking-[-0.04em]">Etsy Profit Calculator</h3><p className="mt-3 text-sm leading-6 text-white/44">Estimate order profit after fees, product cost, shipping and other expenses.</p><span className="resource-link mt-5 inline-flex">Open calculator →</span></a><div className="resource-card group p-6"><div className="flex items-center justify-between"><span className="resource-number">02</span><span className="coming-pill">Coming soon</span></div><div className="resource-icon mt-9">%</div><h3 className="mt-5 text-xl font-semibold tracking-[-0.04em]">Etsy Fee Calculator</h3><p className="mt-3 text-sm leading-6 text-white/44">Estimate the marketplace charges behind a sale before you set your price.</p></div><div className="resource-card group p-6"><div className="flex items-center justify-between"><span className="resource-number">03</span><span className="coming-pill">Coming soon</span></div><div className="resource-icon mt-9">↗</div><h3 className="mt-5 text-xl font-semibold tracking-[-0.04em]">Profit Margin Calculator</h3><p className="mt-3 text-sm leading-6 text-white/44">Turn price and cost into a margin you can actually use for decisions.</p></div></div></section>

      <section id="early-access" className="scroll-section mx-auto max-w-7xl px-5 pb-20 sm:px-8 lg:px-12 lg:pb-24"><div className="cta-card relative overflow-hidden rounded-[2rem] border border-white/[0.09] px-6 py-14 text-center sm:px-12 sm:py-20"><div className="cta-orb"/><div className="relative z-10 mx-auto max-w-3xl"><p className="section-kicker">Early access</p><h2 className="section-title mt-4">Stop guessing what your shop makes.</h2><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-white/52 sm:text-lg">Join the founding list and get first access when private beta onboarding opens.</p><WaitlistForm /></div></div></section>

      <footer className="border-t border-white/[0.06]"><div className="mx-auto max-w-7xl px-6 py-8 text-sm text-white/34 sm:px-8 lg:px-12"><div className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><Image src="/seller-studio-brand-icon.png" alt="" width={28} height={28} className="brand-logo-icon brand-logo-icon-small" /><span className="font-medium tracking-[-0.02em] text-white/72">Seller Studio</span></div><p>Run your shop by profit.</p><div className="flex flex-wrap gap-x-5 gap-y-2"><a className="footer-link" href="/privacy">Privacy</a><a className="footer-link" href="/terms">Terms</a><a className="footer-link" href="/etsy-disclaimer">Etsy disclaimer</a></div></div><div className="mt-6 border-t border-white/[0.05] pt-5 text-xs leading-5 text-white/26"><p>© 2026 Seller Studio. Seller Studio is an independent product and is not affiliated with, endorsed by, or sponsored by Etsy, Inc. Etsy is a trademark of Etsy, Inc.</p></div></div></footer>
    </main>
  );
}

function Metric({label,value,helper}:{label:string;value:string;helper:string}) { return <div><p className="text-xs font-medium uppercase tracking-[0.22em] text-white/35">{label}</p><p className="mt-2 text-2xl font-semibold tracking-[-0.04em] text-white">{value}</p><p className="mt-1 text-sm text-white/42">{helper}</p></div> }
function MoneyRow({label,value,strong=false}:{label:string;value:string;strong?:boolean}) { return <div className="flex items-center justify-between gap-6"><span className={strong?"font-medium text-white/88":"text-white/46"}>{label}</span><span className={strong?"font-semibold text-white":"font-medium text-white/74"}>{value}</span></div> }
function Insight({label,value}:{label:string;value:string}) { return <div className="insight-card"><span>{label}</span><strong>{value}</strong></div> }
function TrustItem({title,text}:{title:string;text:string}) { return <div className="trust-item p-6"><span className="trust-check">✓</span><h3 className="mt-5 text-lg font-semibold tracking-[-0.035em]">{title}</h3><p className="mt-2 text-sm leading-6 text-white/44">{text}</p></div> }
function MiniBenefit({value,label}:{value:string;label:string}) { return <div className="mini-benefit"><strong>{value}</strong><span>{label}</span></div> }
function LivePhoneMock() { return <div className="phone-stage live-phone-stage"><div className="phone-glow live-phone-glow"/><div className="live-phone-float live-phone-float-one"><span>Profit</span><strong>Live</strong></div><div className="live-phone-float live-phone-float-two"><span>Etsy</span><strong>Synced</strong></div><div className="phone-shell live-phone-shell"><div className="live-phone-screen"><Image src="/seller-studio-live-dashboard.png" alt="Live Seller Studio mobile dashboard showing profit, revenue, costs, orders and Etsy sync" fill priority sizes="(max-width: 640px) 270px, 330px" className="live-app-image" /></div></div><div className="live-build-caption"><span className="live-proof-dot"/>Live development build</div></div> }
function ArrowIcon() { return <svg aria-hidden="true" className="h-4 w-4" fill="none" viewBox="0 0 24 24"><path d="M5 12h14M13 6l6 6-6 6" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8"/></svg> }
